import test from 'node:test';
import assert from 'node:assert/strict';
import { evaluateAxiomaticBranch as e } from '../src/runtime.mjs';
import { validateProfile } from '../src/profile.mjs';

const p={schemaVersion:'1.0',name:'test',origin:'customer-modified',policy:{allowedCommands:['./status','./deploy'],allowedTools:['read','write'],mutatingTools:['write'],nonMutatingCommands:['./status']}};
test('profile validates',()=>assert.equal(validateProfile(p).valid,true));
test('RETAIN safe reply',()=>assert.equal(e({profile:p,proposal:{kind:'reply',reply:'ok'}}).decision,'RETAIN'));
test('PRUNE outside command',()=>assert.equal(e({profile:p,proposal:{kind:'command',command:'echo hello'},explicitAction:true}).decision,'PRUNE'));
test('GATE consequential command',()=>assert.equal(e({profile:p,proposal:{kind:'command',command:'./deploy prod'}}).decision,'GATE'));
test('RETAIN explicit command',()=>assert.equal(e({profile:p,proposal:{kind:'command',command:'./deploy prod'},explicitAction:true}).decision,'RETAIN'));
test('PRUNE unknown tool',()=>assert.equal(e({profile:p,proposal:{kind:'tool',tool:'unknown'},explicitAction:true}).decision,'PRUNE'));
test('GATE mutation',()=>assert.equal(e({profile:p,proposal:{kind:'tool',tool:'write'}}).decision,'GATE'));
test('RETAIN explicit mutation',()=>assert.equal(e({profile:p,proposal:{kind:'tool',tool:'write'},explicitAction:true}).decision,'RETAIN'));
test('invalid profile fails closed',()=>assert.equal(e({profile:null,proposal:{kind:'tool',tool:'read'}}).decision,'PRUNE'));
test('profile cannot self-expand tool authority',()=>{const x=structuredClone(p);x.policy.allowedTools=['read'];x.policy.mutatingTools=[];assert.equal(e({profile:x,proposal:{kind:'tool',tool:'write'},explicitAction:true}).decision,'PRUNE')});
test('branch id is deterministic',()=>{const input={profile:p,proposal:{kind:'tool',tool:'read'}};assert.equal(e(input).branchId,e(input).branchId)});
test('PRUNE non-canonical leading command whitespace',()=>assert.equal(e({profile:p,proposal:{kind:'command',command:'  ./deploy prod'},explicitAction:true}).decision,'PRUNE'));
test('PRUNE non-canonical trailing command whitespace',()=>assert.equal(e({profile:p,proposal:{kind:'command',command:'./deploy prod  '},explicitAction:true}).decision,'PRUNE'));
test('PRUNE shell operators in commands',()=>{for(const command of ['./status && ./deploy prod','./status | ./deploy prod','./status\n./deploy prod'])assert.equal(e({profile:p,proposal:{kind:'command',command},explicitAction:true}).decision,'PRUNE')});
test('PRUNE non-string and non-canonical tools',()=>{for(const tool of [['write'],{toString:()=> 'write'},' write','write\n'])assert.equal(e({profile:p,proposal:{kind:'tool',tool},explicitAction:true}).decision,'PRUNE')});
test('PRUNE trailing canonical-tool whitespace',()=>assert.equal(e({profile:p,proposal:{kind:'tool',tool:'write '},explicitAction:true}).decision,'PRUNE'));
test('PRUNE leading canonical-tool whitespace',()=>assert.equal(e({profile:p,proposal:{kind:'tool',tool:' write'},explicitAction:true}).decision,'PRUNE'));
test('PRUNE dot-slash command outside allowlist',()=>assert.equal(e({profile:p,proposal:{kind:'command',command:'./root'},explicitAction:true}).decision,'PRUNE'));
test('PRUNE non-string command values',()=>{for(const command of [['./status'],{toString:()=> './status'},1,true,null])assert.equal(e({profile:p,proposal:{kind:'command',command},explicitAction:true}).decision,'PRUNE')});
test('exact bundled baseline is ZDX Validated',async()=>{const {ZDX_VALIDATED_BASELINE,validateProfile}=await import('../src/profile.mjs');const r=validateProfile(ZDX_VALIDATED_BASELINE);assert.equal(r.valid,true);assert.equal(r.classification,'ZDX Validated')});
test('forged zdx-validated profile fails validation',()=>{const x=structuredClone(p);x.origin='zdx-validated';assert.equal(validateProfile(x).valid,false);assert.equal(validateProfile(x).classification,'Validation Failed')});
test('modified validated baseline cannot retain ZDX status',async()=>{const {ZDX_VALIDATED_BASELINE}=await import('../src/profile.mjs');const x=structuredClone(ZDX_VALIDATED_BASELINE);x.policy.allowedTools.push('write');assert.equal(validateProfile(x).valid,false)});
test('claimed hash field cannot forge validation',async()=>{const {ZDX_VALIDATED_BASELINE,ZDX_VALIDATED_BASELINE_HASH}=await import('../src/profile.mjs');const x=structuredClone(ZDX_VALIDATED_BASELINE);x.name='forged';x.profileHash=ZDX_VALIDATED_BASELINE_HASH;assert.equal(validateProfile(x).valid,false)});
test('customer modified profile remains customer modified',()=>{const r=validateProfile(p);assert.equal(r.valid,true);assert.equal(r.classification,'Customer Modified')});
